import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#354a53",
        "surface-bright": "#f8f9fa",
        "secondary-fixed": "#cfe6f2",
        "primary-fixed": "#92f1fe",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#75d5e2",
        "primary-container": "#00838f",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#3e494a",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#604100",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#526772",
        "on-primary-fixed-variant": "#004f56",
        "surface-tint": "#006972",
        background: "#f8f9fa",
        "tertiary-fixed": "#ffdeac",
        "on-tertiary-fixed": "#281900",
        primary: "#006872",
        outline: "#6e797b",
        "on-background": "#191c1d",
        "on-secondary-fixed": "#071e27",
        "on-error-container": "#93000a",
        "surface-container": "#edeeef",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#bdc9ca",
        secondary: "#4c616c",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        surface: "#f8f9fa",
        tertiary: "#7e5600",
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#75d5e2",
        "tertiary-container": "#9e6d00",
        "on-error": "#ffffff",
        "secondary-container": "#cfe6f2",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#001f23",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffba38",
        "secondary-fixed-dim": "#b4cad6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
